param(
  [string]$DevBackendUrl = "https://label-backend-dev-ptat4y7djq-uc.a.run.app",
  [switch]$UseProdBackend
)

$root = Resolve-Path (Join-Path $PSScriptRoot "..")
$frontendDir = Join-Path $root "frontend"
$mainEnvFile = Join-Path $root ".env"
$frontendEnvFile = Join-Path $frontendDir ".env.local"

# ---------- Read main .env to get Firebase config ----------

function Read-DotEnvValue {
  param(
    [string]$Path,
    [string]$Key
  )

  if (!(Test-Path $Path)) {
    return $null
  }

  foreach ($line in Get-Content $Path) {
    $trimmed = $line.Trim()
    if ($trimmed.Length -eq 0 -or $trimmed.StartsWith("#")) {
      continue
    }

    if ($trimmed -match "^\s*([^=]+?)\s*=\s*(.*)\s*$") {
      $currentKey = $Matches[1].Trim()
      if ($currentKey -ne $Key) {
        continue
      }

      $value = $Matches[2].Trim()
      if (($value.StartsWith('"') -and $value.EndsWith('"')) -or ($value.StartsWith("'") -and $value.EndsWith("'"))) {
        $value = $value.Substring(1, $value.Length - 2)
      } else {
        $hashIndex = $value.IndexOf("#")
        if ($hashIndex -ge 0) {
          $value = $value.Substring(0, $hashIndex).Trim()
        }
      }

      return $value
    }
  }

  return $null
}

# Get Firebase config from main .env
$firebaseApiKey = Read-DotEnvValue -Path $mainEnvFile -Key "VITE_FIREBASE_API_KEY"
$firebaseAuthDomain = Read-DotEnvValue -Path $mainEnvFile -Key "VITE_FIREBASE_AUTH_DOMAIN"
$firebaseProjectId = Read-DotEnvValue -Path $mainEnvFile -Key "VITE_FIREBASE_PROJECT_ID"
$firebaseStorageBucket = Read-DotEnvValue -Path $mainEnvFile -Key "VITE_FIREBASE_STORAGE_BUCKET"
$firebaseMessagingSenderId = Read-DotEnvValue -Path $mainEnvFile -Key "VITE_FIREBASE_MESSAGING_SENDER_ID"
$firebaseAppId = Read-DotEnvValue -Path $mainEnvFile -Key "VITE_FIREBASE_APP_ID"
$firebaseMeasurementId = Read-DotEnvValue -Path $mainEnvFile -Key "VITE_FIREBASE_MEASUREMENT_ID"

# Determine backend URL
$backendUrl = if ($UseProdBackend) {
  $prodUrl = Read-DotEnvValue -Path $mainEnvFile -Key "VITE_API_BASE_URL"
  if (-not $prodUrl) {
    throw "VITE_API_BASE_URL not found in .env for production backend"
  }
  Write-Host "Using PRODUCTION backend: $prodUrl" -ForegroundColor Yellow
  $prodUrl
} else {
  Write-Host "Using DEV backend: $DevBackendUrl" -ForegroundColor Cyan
  $DevBackendUrl
}

# ---------- Create frontend .env.local ----------

$envContent = @"
# Auto-generated by run_frontend_dev.ps1
# This file overrides .env for local development pointing to DEV backend

VITE_API_BASE_URL=$backendUrl
VITE_FIREBASE_API_KEY=$firebaseApiKey
VITE_FIREBASE_AUTH_DOMAIN=$firebaseAuthDomain
VITE_FIREBASE_PROJECT_ID=$firebaseProjectId
VITE_FIREBASE_STORAGE_BUCKET=$firebaseStorageBucket
VITE_FIREBASE_MESSAGING_SENDER_ID=$firebaseMessagingSenderId
VITE_FIREBASE_APP_ID=$firebaseAppId
VITE_FIREBASE_MEASUREMENT_ID=$firebaseMeasurementId
"@

Set-Content -Path $frontendEnvFile -Value $envContent -Encoding UTF8
Write-Host ""
Write-Host "Created $frontendEnvFile with backend URL: $backendUrl"
Write-Host ""

# ---------- Run pnpm dev ----------

Push-Location $frontendDir
try {
  Write-Host "=== Starting frontend dev server ==="
  Write-Host ""
  pnpm run dev
} finally {
  Pop-Location
}
